SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

-- --------------------------------------------------------

--
-- Table structure for table `fm_chats`
--

CREATE TABLE IF NOT EXISTS `fm_chats` (
  `id` int(10) NOT NULL,
  `admin_id` int(10) NOT NULL,
  `name` varchar(200) NOT NULL,
  `image` varchar(50) DEFAULT NULL,
  `descr` varchar(1000) DEFAULT NULL,
  `fdate` varchar(10) DEFAULT NULL,
  `city` varchar(40) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `fm_msgs`
--

CREATE TABLE IF NOT EXISTS `fm_msgs` (
  `id` int(11) NOT NULL,
  `chat_id` int(10) NOT NULL,
  `user_id` int(10) NOT NULL,
  `text` varchar(3000) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8;

--
-- Triggers `fm_msgs`
--
DELIMITER $$
CREATE TRIGGER `mat_filter` BEFORE INSERT ON `fm_msgs`
 FOR EACH ROW begin
    DECLARE isMat int(1) default 0;

    SELECT 1 INTO isMat from fm_users where (
        new.text LIKE '%жопа%' 
        OR new.text LIKE '%сука%' 
        OR new.text LIKE '%суки%' 
        OR new.text LIKE '%бля%' 
        OR new.text LIKE '%ебать%'
        OR new.text LIKE '%пидор%'
        OR new.text LIKE '%пидр%'
        OR new.text LIKE '%уебок%'
         OR new.text LIKE '%6ля%'
         OR new.text LIKE '%6лядь%'
         OR new.text LIKE '%6лять%'
         OR new.text LIKE '%b3ъeб%'
         OR new.text LIKE '%cock%'
         OR new.text LIKE '%cunt%'
         OR new.text LIKE '%e6aль%'
         OR new.text LIKE '%ebal%'
         OR new.text LIKE '%eblan%'
         OR new.text LIKE '%eбaл%'
         OR new.text LIKE '%eбaть%'
         OR new.text LIKE '%eбyч%'
         OR new.text LIKE '%eбать%'
         OR new.text LIKE '%eбёт%'
         OR new.text LIKE '%eблантий%'
         OR new.text LIKE '%fuck%'
         OR new.text LIKE '%fucker%'
         OR new.text LIKE '%fucking%'
         OR new.text LIKE '%xyёв%'
         OR new.text LIKE '%xyй%'
         OR new.text LIKE '%xyя%'
         OR new.text LIKE '%xуе,xуй%'
         OR new.text LIKE '%xую%'
         OR new.text LIKE '%zaeb%'
         OR new.text LIKE '%zaebal%'
         OR new.text LIKE '%zaebali%'
         OR new.text LIKE '%zaebat%'
         OR new.text LIKE '%архипиздрит%'
         OR new.text LIKE '%ахуел%'
         OR new.text LIKE '%ахуеть%'
         OR new.text LIKE '%бздение%'
         OR new.text LIKE '%бздеть%'
         OR new.text LIKE '%бздех%'
         OR new.text LIKE '%бздецы%'
         OR new.text LIKE '%бздит%'
         OR new.text LIKE '%бздицы%'
         OR new.text LIKE '%бздло%'
         OR new.text LIKE '%бзднуть%'
         OR new.text LIKE '%бздун%'
         OR new.text LIKE '%бздунья%'
         OR new.text LIKE '%бздюха%'
         OR new.text LIKE '%бздюшка%'
         OR new.text LIKE '%бздюшко%'
         OR new.text LIKE '%бля%'
         OR new.text LIKE '%блябу%'
         OR new.text LIKE '%блябуду%'
         OR new.text LIKE '%бляд%'
         OR new.text LIKE '%бляди%'
         OR new.text LIKE '%блядина%'
         OR new.text LIKE '%блядище%'
         OR new.text LIKE '%блядки%'
         OR new.text LIKE '%блядовать%'
         OR new.text LIKE '%блядство%'
         OR new.text LIKE '%блядун%'
         OR new.text LIKE '%блядуны%'
         OR new.text LIKE '%блядунья%'
         OR new.text LIKE '%блядь%'
         OR new.text LIKE '%блядюга%'
         OR new.text LIKE '%блять%'
         OR new.text LIKE '%вафел%'
         OR new.text LIKE '%вафлёр%'
         OR new.text LIKE '%взъебка%'
         OR new.text LIKE '%взьебка%'
         OR new.text LIKE '%взьебывать%'
         OR new.text LIKE '%въеб%'
         OR new.text LIKE '%въебался%'
         OR new.text LIKE '%въебенн%'
         OR new.text LIKE '%въебусь%'
         OR new.text LIKE '%въебывать%'
         OR new.text LIKE '%выблядок%'
         OR new.text LIKE '%выблядыш%'
         OR new.text LIKE '%выеб%'
         OR new.text LIKE '%выебать%'
         OR new.text LIKE '%выебен%'
         OR new.text LIKE '%выебнулся%'
         OR new.text LIKE '%выебон%'
         OR new.text LIKE '%выебываться%'
         OR new.text LIKE '%выпердеть%'
         OR new.text LIKE '%высраться%'
         OR new.text LIKE '%выссаться%'
         OR new.text LIKE '%вьебен%'
         OR new.text LIKE '%гавно%'
         OR new.text LIKE '%гавнюк%'
         OR new.text LIKE '%гавнючка%'
         OR new.text LIKE '%гамно%'
         OR new.text LIKE '%гандон%'
         OR new.text LIKE '%гнид%'
         OR new.text LIKE '%гнида%'
         OR new.text LIKE '%гниды%'
         OR new.text LIKE '%говенка%'
         OR new.text LIKE '%говенный%'
         OR new.text LIKE '%говешка%'
         OR new.text LIKE '%говназия%'
         OR new.text LIKE '%говнецо%'
         OR new.text LIKE '%говнище%'
         OR new.text LIKE '%говно%'
         OR new.text LIKE '%говноед%'
         OR new.text LIKE '%говнолинк%'
         OR new.text LIKE '%говночист%'
         OR new.text LIKE '%говнюк%'
         OR new.text LIKE '%говнюха%'
         OR new.text LIKE '%говнядина%'
         OR new.text LIKE '%говняк%'
         OR new.text LIKE '%говняный%'
         OR new.text LIKE '%говнять%'
         OR new.text LIKE '%гондон%'
         OR new.text LIKE '%доебываться%'
         OR new.text LIKE '%долбоеб%'
         OR new.text LIKE '%долбоёб%'
         OR new.text LIKE '%долбоящер%'
         OR new.text LIKE '%дрисня%'
         OR new.text LIKE '%дрист%'
         OR new.text LIKE '%дристануть%'
         OR new.text LIKE '%дристать%'
         OR new.text LIKE '%дристун%'
         OR new.text LIKE '%дристуха%'
         OR new.text LIKE '%дрочелло%'
         OR new.text LIKE '%дрочена%'
         OR new.text LIKE '%дрочила%'
         OR new.text LIKE '%дрочилка%'
         OR new.text LIKE '%дрочистый%'
         OR new.text LIKE '%дрочить%'
         OR new.text LIKE '%дрочка%'
         OR new.text LIKE '%дрочун%'
         OR new.text LIKE '%е6ал%'
         OR new.text LIKE '%е6ут%'
         OR new.text LIKE '%еб твою мать%'
         OR new.text LIKE '%ёб твою мать%'
         OR new.text LIKE '%ёбaн%'
         OR new.text LIKE '%ебaть%'
         OR new.text LIKE '%ебyч%'
         OR new.text LIKE '%ебал%'
         OR new.text LIKE '%ебало%'
         OR new.text LIKE '%ебальник%'
         OR new.text LIKE '%ебан%'
         OR new.text LIKE '%ебанамать%'
         OR new.text LIKE '%ебанат%'
         OR new.text LIKE '%ебаная%'
         OR new.text LIKE '%ёбаная%'
         OR new.text LIKE '%ебанический%'
         OR new.text LIKE '%ебанный%'
         OR new.text LIKE '%ебанныйврот%'
         OR new.text LIKE '%ебаное%'
         OR new.text LIKE '%ебануть%'
         OR new.text LIKE '%ебануться%'
         OR new.text LIKE '%ёбаную%'
         OR new.text LIKE '%ебаный%'
         OR new.text LIKE '%ебанько%'
         OR new.text LIKE '%ебарь%'
         OR new.text LIKE '%ебат%'
         OR new.text LIKE '%ёбат%'
         OR new.text LIKE '%ебатория%'
         OR new.text LIKE '%ебать%'
         OR new.text LIKE '%ебать-копать%'
         OR new.text LIKE '%ебаться%'
         OR new.text LIKE '%ебашить%'
         OR new.text LIKE '%ебёна%'
         OR new.text LIKE '%ебет%'
         OR new.text LIKE '%ебёт%'
         OR new.text LIKE '%ебец%'
         OR new.text LIKE '%ебик%'
         OR new.text LIKE '%ебин%'
         OR new.text LIKE '%ебись%'
         OR new.text LIKE '%ебическая%'
         OR new.text LIKE '%ебки%'
         OR new.text LIKE '%ебла%'
         OR new.text LIKE '%еблан%'
         OR new.text LIKE '%ебливый%'
         OR new.text LIKE '%еблище%'
         OR new.text LIKE '%ебло%'
         OR new.text LIKE '%еблыст%'
         OR new.text LIKE '%ебля%'
         OR new.text LIKE '%ёбн%'
         OR new.text LIKE '%ебнуть%'
         OR new.text LIKE '%ебнуться%'
         OR new.text LIKE '%ебня%'
         OR new.text LIKE '%ебошить%'
         OR new.text LIKE '%ебская%'
         OR new.text LIKE '%ебский%'
         OR new.text LIKE '%ебтвоюмать%'
         OR new.text LIKE '%ебун%'
         OR new.text LIKE '%ебут%'
         OR new.text LIKE '%ебуч%'
         OR new.text LIKE '%ебуче%'
         OR new.text LIKE '%ебучее%'
         OR new.text LIKE '%ебучий%'
         OR new.text LIKE '%ебучим%'
         OR new.text LIKE '%ебущ%'
         OR new.text LIKE '%ебырь%'
         OR new.text LIKE '%елда%'
         OR new.text LIKE '%елдак%'
         OR new.text LIKE '%елдачить%'
         OR new.text LIKE '%жопа%'
         OR new.text LIKE '%жопу%'
         OR new.text LIKE '%заговнять%'
         OR new.text LIKE '%задрачивать%'
         OR new.text LIKE '%задристать%'
         OR new.text LIKE '%задрота%'
         OR new.text LIKE '%зае6%'
         OR new.text LIKE '%заё6%'
         OR new.text LIKE '%заеб%'
         OR new.text LIKE '%заёб%'
         OR new.text LIKE '%заеба%'
         OR new.text LIKE '%заебал%'
         OR new.text LIKE '%заебанец%'
         OR new.text LIKE '%заебастая%'
         OR new.text LIKE '%заебастый%'
         OR new.text LIKE '%заебать%'
         OR new.text LIKE '%заебаться%'
         OR new.text LIKE '%заебашить%'
         OR new.text LIKE '%заебистое%'
         OR new.text LIKE '%заёбистое%'
         OR new.text LIKE '%заебистые%'
         OR new.text LIKE '%заёбистые%'
         OR new.text LIKE '%заебистый%'
         OR new.text LIKE '%заёбистый%'
         OR new.text LIKE '%заебись%'
         OR new.text LIKE '%заебошить%'
         OR new.text LIKE '%заебываться%'
         OR new.text LIKE '%залуп%'
         OR new.text LIKE '%залупа%'
         OR new.text LIKE '%залупаться%'
         OR new.text LIKE '%залупить%'
         OR new.text LIKE '%залупиться%'
         OR new.text LIKE '%замудохаться%'
         OR new.text LIKE '%запиздячить%'
         OR new.text LIKE '%засерать%'
         OR new.text LIKE '%засерун%'
         OR new.text LIKE '%засеря%'
         OR new.text LIKE '%засирать%'
         OR new.text LIKE '%засрун%'
         OR new.text LIKE '%захуячить%'
         OR new.text LIKE '%заябестая%'
         OR new.text LIKE '%злоеб%'
         OR new.text LIKE '%злоебучая%'
         OR new.text LIKE '%злоебучее%'
         OR new.text LIKE '%злоебучий%'
         OR new.text LIKE '%ибанамат%'
         OR new.text LIKE '%ибонех%'
         OR new.text LIKE '%изговнять%'
         OR new.text LIKE '%изговняться%'
         OR new.text LIKE '%изъебнуться%'
         OR new.text LIKE '%ипать%'
         OR new.text LIKE '%ипаться%'
         OR new.text LIKE '%ипаццо%'
         OR new.text LIKE '%Какдвапальцаобоссать%'
         OR new.text LIKE '%конча%'
         OR new.text LIKE '%курва%'
         OR new.text LIKE '%курвятник%'
         OR new.text LIKE '%лох%'
         OR new.text LIKE '%лошарa%'
         OR new.text LIKE '%лошара%'
         OR new.text LIKE '%лошары%'
         OR new.text LIKE '%лошок%'
         OR new.text LIKE '%лярва%'
         OR new.text LIKE '%малафья%'
         OR new.text LIKE '%манда%'
         OR new.text LIKE '%мандавошек%'
         OR new.text LIKE '%мандавошка%'
         OR new.text LIKE '%мандавошки%'
         OR new.text LIKE '%мандей%'
         OR new.text LIKE '%мандень%'
         OR new.text LIKE '%мандеть%'
         OR new.text LIKE '%мандища%'
         OR new.text LIKE '%мандой%'
         OR new.text LIKE '%манду%'
         OR new.text LIKE '%мандюк%'
         OR new.text LIKE '%минет%'
         OR new.text LIKE '%минетчик%'
         OR new.text LIKE '%минетчица%'
         OR new.text LIKE '%млять%'
         OR new.text LIKE '%мокрощелка%'
         OR new.text LIKE '%мокрощёлка%'
         OR new.text LIKE '%мразь%'
         OR new.text LIKE '%мудak%'
         OR new.text LIKE '%мудaк%'
         OR new.text LIKE '%мудаг%'
         OR new.text LIKE '%мудак%'
         OR new.text LIKE '%муде%'
         OR new.text LIKE '%мудель%'
         OR new.text LIKE '%мудеть%'
         OR new.text LIKE '%муди%'
         OR new.text LIKE '%мудил%'
         OR new.text LIKE '%мудила%'
         OR new.text LIKE '%мудистый%'
         OR new.text LIKE '%мудня%'
         OR new.text LIKE '%мудоеб%'
         OR new.text LIKE '%мудозвон%'
         OR new.text LIKE '%мудоклюй%'
         OR new.text LIKE '%на хер%'
         OR new.text LIKE '%на хуй%'
         OR new.text LIKE '%набздел%'
         OR new.text LIKE '%набздеть%'
         OR new.text LIKE '%наговнять%'
         OR new.text LIKE '%надристать%'
         OR new.text LIKE '%надрочить%'
         OR new.text LIKE '%наебать%'
         OR new.text LIKE '%наебет%'
         OR new.text LIKE '%наебнуть%'
         OR new.text LIKE '%наебнуться%'
         OR new.text LIKE '%наебывать%'
         OR new.text LIKE '%напиздел%'
         OR new.text LIKE '%напиздели%'
         OR new.text LIKE '%напиздело%'
         OR new.text LIKE '%напиздили%'
         OR new.text LIKE '%насрать%'
         OR new.text LIKE '%настопиздить%'
         OR new.text LIKE '%нахер%'
         OR new.text LIKE '%нахрен%'
         OR new.text LIKE '%нахуй%'
         OR new.text LIKE '%нахуйник%'
         OR new.text LIKE '%не ебет%'
         OR new.text LIKE '%не ебёт%'
         OR new.text LIKE '%невротебучий%'
         OR new.text LIKE '%невъебенно%'
         OR new.text LIKE '%нехира%'
         OR new.text LIKE '%нехрен%'
         OR new.text LIKE '%Нехуй%'
         OR new.text LIKE '%нехуйственно%'
         OR new.text LIKE '%ниибацо%'
         OR new.text LIKE '%ниипацца%'
         OR new.text LIKE '%ниипаццо%'
         OR new.text LIKE '%ниипет%'
         OR new.text LIKE '%никуя%'
         OR new.text LIKE '%нихера%'
         OR new.text LIKE '%нихуя%'
         OR new.text LIKE '%обдристаться%'
         OR new.text LIKE '%обосранец%'
         OR new.text LIKE '%обосрать%'
         OR new.text LIKE '%обосцать%'
         OR new.text LIKE '%обосцаться%'
         OR new.text LIKE '%обсирать%'
         OR new.text LIKE '%объебос%'
         OR new.text LIKE '%обьебать обьебос%'
         OR new.text LIKE '%однохуйственно%'
         OR new.text LIKE '%опездал%'
         OR new.text LIKE '%опизде%'
         OR new.text LIKE '%опизденивающе%'
         OR new.text LIKE '%остоебенить%'
         OR new.text LIKE '%остопиздеть%'
         OR new.text LIKE '%отмудохать%'
         OR new.text LIKE '%отпиздить%'
         OR new.text LIKE '%отпиздячить%'
         OR new.text LIKE '%отпороть%'
         OR new.text LIKE '%отъебись%'
         OR new.text LIKE '%охуевательский%'
         OR new.text LIKE '%охуевать%'
         OR new.text LIKE '%охуевающий%'
         OR new.text LIKE '%охуел%'
         OR new.text LIKE '%охуенно%'
         OR new.text LIKE '%охуеньчик%'
         OR new.text LIKE '%охуеть%'
         OR new.text LIKE '%охуительно%'
         OR new.text LIKE '%охуительный%'
         OR new.text LIKE '%охуяньчик%'
         OR new.text LIKE '%охуячивать%'
         OR new.text LIKE '%охуячить%'
         OR new.text LIKE '%очкун%'
         OR new.text LIKE '%падла%'
         OR new.text LIKE '%падонки%'
         OR new.text LIKE '%падонок%'
         OR new.text LIKE '%паскуда%'
         OR new.text LIKE '%педерас%'
         OR new.text LIKE '%педик%'
         OR new.text LIKE '%педрик%'
         OR new.text LIKE '%педрила%'
         OR new.text LIKE '%педрилло%'
         OR new.text LIKE '%педрило%'
         OR new.text LIKE '%педрилы%'
         OR new.text LIKE '%пездень%'
         OR new.text LIKE '%пездит%'
         OR new.text LIKE '%пездишь%'
         OR new.text LIKE '%пездо%'
         OR new.text LIKE '%пездят%'
         OR new.text LIKE '%пердануть%'
         OR new.text LIKE '%пердеж%'
         OR new.text LIKE '%пердение%'
         OR new.text LIKE '%пердеть%'
         OR new.text LIKE '%пердильник%'
         OR new.text LIKE '%перднуть%'
         OR new.text LIKE '%пёрднуть%'
         OR new.text LIKE '%пердун%'
         OR new.text LIKE '%пердунец%'
         OR new.text LIKE '%пердунина%'
         OR new.text LIKE '%пердунья%'
         OR new.text LIKE '%пердуха%'
         OR new.text LIKE '%пердь%'
         OR new.text LIKE '%переёбок%'
         OR new.text LIKE '%пернуть%'
         OR new.text LIKE '%пёрнуть%'
         OR new.text LIKE '%пи3д%'
         OR new.text LIKE '%пи3де%'
         OR new.text LIKE '%пи3ду%'
         OR new.text LIKE '%пиzдец%'
         OR new.text LIKE '%пидар%'
         OR new.text LIKE '%пидарaс%'
         OR new.text LIKE '%пидарас%'
         OR new.text LIKE '%пидарасы%'
         OR new.text LIKE '%пидары%'
         OR new.text LIKE '%пидор%'
         OR new.text LIKE '%пидорасы%'
         OR new.text LIKE '%пидорка%'
         OR new.text LIKE '%пидорок%'
         OR new.text LIKE '%пидоры%'
         OR new.text LIKE '%пидрас%'
         OR new.text LIKE '%пизда%'
         OR new.text LIKE '%пиздануть%'
         OR new.text LIKE '%пиздануться%'
         OR new.text LIKE '%пиздарваньчик%'
         OR new.text LIKE '%пиздато%'
         OR new.text LIKE '%пиздатое%'
         OR new.text LIKE '%пиздатый%'
         OR new.text LIKE '%пизденка%'
         OR new.text LIKE '%пизденыш%'
         OR new.text LIKE '%пиздёныш%'
         OR new.text LIKE '%пиздеть%'
         OR new.text LIKE '%пиздец%'
         OR new.text LIKE '%пиздит%'
         OR new.text LIKE '%пиздить%'
         OR new.text LIKE '%пиздиться%'
         OR new.text LIKE '%пиздишь%'
         OR new.text LIKE '%пиздища%'
         OR new.text LIKE '%пиздище%'
         OR new.text LIKE '%пиздобол%'
         OR new.text LIKE '%пиздоболы%'
         OR new.text LIKE '%пиздобратия%'
         OR new.text LIKE '%пиздоватая%'
         OR new.text LIKE '%пиздоватый%'
         OR new.text LIKE '%пиздолиз%'
         OR new.text LIKE '%пиздонутые%'
         OR new.text LIKE '%пиздорванец%'
         OR new.text LIKE '%пиздорванка%'
         OR new.text LIKE '%пиздострадатель%'
         OR new.text LIKE '%пизду%'
         OR new.text LIKE '%пиздуй%'
         OR new.text LIKE '%пиздун%'
         OR new.text LIKE '%пиздунья%'
         OR new.text LIKE '%пизды%'
         OR new.text LIKE '%пиздюга%'
         OR new.text LIKE '%пиздюк%'
         OR new.text LIKE '%пиздюлина%'
         OR new.text LIKE '%пиздюля%'
         OR new.text LIKE '%пиздят%'
         OR new.text LIKE '%пиздячить%'
         OR new.text LIKE '%писбшки%'
         OR new.text LIKE '%писька%'
         OR new.text LIKE '%писькострадатель%'
         OR new.text LIKE '%писюн%'
         OR new.text LIKE '%писюшка%'
         OR new.text LIKE '%по хуй%'
         OR new.text LIKE '%по хую%'
         OR new.text LIKE '%подговнять%'
         OR new.text LIKE '%подонки%'
         OR new.text LIKE '%подонок%'
         OR new.text LIKE '%подъебнуть%'
         OR new.text LIKE '%подъебнуться%'
         OR new.text LIKE '%поебать%'
         OR new.text LIKE '%поебень%'
         OR new.text LIKE '%поёбываает%'
         OR new.text LIKE '%поскуда%'
         OR new.text LIKE '%посрать%'
         OR new.text LIKE '%потаскуха%'
         OR new.text LIKE '%потаскушка%'
         OR new.text LIKE '%похер%'
         OR new.text LIKE '%похерил%'
         OR new.text LIKE '%похерила%'
         OR new.text LIKE '%похерили%'
         OR new.text LIKE '%похеру%'
         OR new.text LIKE '%похрен%'
         OR new.text LIKE '%похрену%'
         OR new.text LIKE '%похуй%'
         OR new.text LIKE '%похуист%'
         OR new.text LIKE '%похуистка%'
         OR new.text LIKE '%похую%'
         OR new.text LIKE '%придурок%'
         OR new.text LIKE '%приебаться%'
         OR new.text LIKE '%припиздень%'
         OR new.text LIKE '%припизднутый%'
         OR new.text LIKE '%припиздюлина%'
         OR new.text LIKE '%пробзделся%'
         OR new.text LIKE '%проблядь%'
         OR new.text LIKE '%проеб%'
         OR new.text LIKE '%проебанка%'
         OR new.text LIKE '%проебать%'
         OR new.text LIKE '%промандеть%'
         OR new.text LIKE '%промудеть%'
         OR new.text LIKE '%пропизделся%'
         OR new.text LIKE '%пропиздеть%'
         OR new.text LIKE '%пропиздячить%'
         OR new.text LIKE '%раздолбай%'
         OR new.text LIKE '%разхуячить%'
         OR new.text LIKE '%разъеб%'
         OR new.text LIKE '%разъеба%'
         OR new.text LIKE '%разъебай%'
         OR new.text LIKE '%разъебать%'
         OR new.text LIKE '%распиздай%'
         OR new.text LIKE '%распиздеться%'
         OR new.text LIKE '%распиздяй%'
         OR new.text LIKE '%распиздяйство%'
         OR new.text LIKE '%распроеть%'
         OR new.text LIKE '%сволота%'
         OR new.text LIKE '%сволочь%'
         OR new.text LIKE '%сговнять%'
         OR new.text LIKE '%секель%'
         OR new.text LIKE '%серун%'
         OR new.text LIKE '%серька%'
         OR new.text LIKE '%сестроеб%'
         OR new.text LIKE '%сикель%'
         OR new.text LIKE '%сила%'
         OR new.text LIKE '%сирать%'
         OR new.text LIKE '%сирывать%'
         OR new.text LIKE '%соси%'
         OR new.text LIKE '%спиздел%'
         OR new.text LIKE '%спиздеть%'
         OR new.text LIKE '%спиздил%'
         OR new.text LIKE '%спиздила%'
         OR new.text LIKE '%спиздили%'
         OR new.text LIKE '%спиздит%'
         OR new.text LIKE '%спиздить%'
         OR new.text LIKE '%срака%'
         OR new.text LIKE '%сраку%'
         OR new.text LIKE '%сраный%'
         OR new.text LIKE '%сранье%'
         OR new.text LIKE '%срать%'
         OR new.text LIKE '%срун%'
         OR new.text LIKE '%ссака%'
         OR new.text LIKE '%ссышь%'
         OR new.text LIKE '%стерва%'
         OR new.text LIKE '%страхопиздище%'
         OR new.text LIKE '%сука%'
         OR new.text LIKE '%суки%'
         OR new.text LIKE '%суходрочка%'
         OR new.text LIKE '%сучара%'
         OR new.text LIKE '%сучий%'
         OR new.text LIKE '%сучка%'
         OR new.text LIKE '%сучко%'
         OR new.text LIKE '%сучонок%'
         OR new.text LIKE '%сучье%'
         OR new.text LIKE '%сцание%'
         OR new.text LIKE '%сцать%'
         OR new.text LIKE '%сцука%'
         OR new.text LIKE '%сцуки%'
         OR new.text LIKE '%сцуконах%'
         OR new.text LIKE '%сцуль%'
         OR new.text LIKE '%сцыха%'
         OR new.text LIKE '%сцышь%'
         OR new.text LIKE '%съебаться%'
         OR new.text LIKE '%сыкун%'
         OR new.text LIKE '%трахае6%'
         OR new.text LIKE '%трахаеб%'
         OR new.text LIKE '%трахаёб%'
         OR new.text LIKE '%трахатель%'
         OR new.text LIKE '%ублюдок%'
         OR new.text LIKE '%уебать%'
         OR new.text LIKE '%уёбища%'
         OR new.text LIKE '%уебище%'
         OR new.text LIKE '%уёбище%'
         OR new.text LIKE '%уебищное%'
         OR new.text LIKE '%уёбищное%'
         OR new.text LIKE '%уебк%'
         OR new.text LIKE '%уебки%'
         OR new.text LIKE '%уёбки%'
         OR new.text LIKE '%уебок%'
         OR new.text LIKE '%уёбок%'
         OR new.text LIKE '%урюк%'
         OR new.text LIKE '%усраться%'
         OR new.text LIKE '%ушлепок%'
         OR new.text LIKE '%х_у_я_р_а%'
         OR new.text LIKE '%хyё%'
         OR new.text LIKE '%хyй%'
         OR new.text LIKE '%хyйня%'
         OR new.text LIKE '%хамло%'
         OR new.text LIKE '%хер%'
         OR new.text LIKE '%херня%'
         OR new.text LIKE '%херовато%'
         OR new.text LIKE '%херовина%'
         OR new.text LIKE '%херовый%'
         OR new.text LIKE '%хитровыебанный%'
         OR new.text LIKE '%хитрожопый%'
         OR new.text LIKE '%хуeм%'
         OR new.text LIKE '%хуе%'
         OR new.text LIKE '%хуё%'
         OR new.text LIKE '%хуевато%'
         OR new.text LIKE '%хуёвенький%'
         OR new.text LIKE '%хуевина%'
         OR new.text LIKE '%хуево%'
         OR new.text LIKE '%хуевый%'
         OR new.text LIKE '%хуёвый%'
         OR new.text LIKE '%хуек%'
         OR new.text LIKE '%хуёк%'
         OR new.text LIKE '%хуел%'
         OR new.text LIKE '%хуем%'
         OR new.text LIKE '%хуенч%'
         OR new.text LIKE '%хуеныш%'
         OR new.text LIKE '%хуенький%'
         OR new.text LIKE '%хуеплет%'
         OR new.text LIKE '%хуеплёт%'
         OR new.text LIKE '%хуепромышленник%'
         OR new.text LIKE '%хуерик%'
         OR new.text LIKE '%хуерыло%'
         OR new.text LIKE '%хуесос%'
         OR new.text LIKE '%хуесоска%'
         OR new.text LIKE '%хуета%'
         OR new.text LIKE '%хуетень%'
         OR new.text LIKE '%хуею%'
         OR new.text LIKE '%хуи%'
         OR new.text LIKE '%хуй%'
         OR new.text LIKE '%хуйком%'
         OR new.text LIKE '%хуйло%'
         OR new.text LIKE '%хуйня%'
         OR new.text LIKE '%хуйрик%'
         OR new.text LIKE '%хуище%'
         OR new.text LIKE '%хуля%'
         OR new.text LIKE '%хую%'
         OR new.text LIKE '%хуюл%'
         OR new.text LIKE '%хуя%'
         OR new.text LIKE '%хуяк%'
         OR new.text LIKE '%хуякать%'
         OR new.text LIKE '%хуякнуть%'
         OR new.text LIKE '%хуяра%'
         OR new.text LIKE '%хуясе%'
         OR new.text LIKE '%хуячить%'
         OR new.text LIKE '%целка%'
         OR new.text LIKE '%чмо%'
         OR new.text LIKE '%чмошник%'
         OR new.text LIKE '%чмырь%'
         OR new.text LIKE '%шалава%'
         OR new.text LIKE '%шалавой%'
         OR new.text LIKE '%шараёбиться%'
         OR new.text LIKE '%шлюха%'
         OR new.text LIKE '%шлюхой%'
         OR new.text LIKE '%шлюшка%'
         OR new.text LIKE '%ябывает%'
    )  LIMIT 1;

    IF 
      (isMat = 1)
    THEN
      SET new.text = "!@#$%";
    END IF;

end
$$
DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `fm_refs`
--

CREATE TABLE IF NOT EXISTS `fm_refs` (
  `user_id` int(10) NOT NULL,
  `chat_id` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `fm_users`
--

CREATE TABLE IF NOT EXISTS `fm_users` (
  `id` int(10) NOT NULL,
  `socnet` int(1) NOT NULL,
  `socuserid` bigint(20) NOT NULL,
  `name` varchar(200) DEFAULT NULL,
  `descr` varchar(200) NOT NULL DEFAULT '',
  `image` varchar(50) NOT NULL DEFAULT ''
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fm_chats`
--
ALTER TABLE `fm_chats`
  ADD PRIMARY KEY (`id`), ADD KEY `admin_id` (`admin_id`);

--
-- Indexes for table `fm_msgs`
--
ALTER TABLE `fm_msgs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `fm_users`
--
ALTER TABLE `fm_users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fm_chats`
--
ALTER TABLE `fm_chats`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=73;
--
-- AUTO_INCREMENT for table `fm_msgs`
--
ALTER TABLE `fm_msgs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=74;
--
-- AUTO_INCREMENT for table `fm_users`
--
ALTER TABLE `fm_users`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=8;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
